import 'dotenv/config';
import { db } from './db/index';
import * as schema from './db/schema';

const seedEvents = [
  {
    id: 'debate-competition',
    title: 'Debate Competition',
    short_description: 'Words have power — prove it. Clash of minds, ideas, and voices.',
    description: 'The Debate Competition at VOXERA is a dynamic platform where ideas clash, perspectives evolve, and voices rise with confidence. Whether you are a seasoned debater or a first-time orator, this is your stage to speak truth to power and challenge the status quo. Compete across 3 intense rounds on thought-provoking topics that matter today.',
    date: '2026-03-16',
    time: '10:00 AM – 1:00 PM',
    location: 'Seminar Hall',
    category: 'Literary',
    registration_fee_single: 99,
    registration_fee_team: 150,
    team_size_min: 1,
    team_size_max: 2,
    team_size: '1-2',
    prize: 'Exciting Gifts + Certificate',
    google_form_url: 'https://forms.gle/Tu7nF2xuPe6bGG1aA',
    rounds: [
      { title: 'Round 1 — Preliminary', description: 'Is Gen Z More Socially Responsible Than Millennials? Individual judging; top performers advance to the next round.' },
      { title: 'Round 2 — Semi-Final', description: 'Is Media Still the Fourth Pillar of Democracy? Elevated difficulty; evaluated on argumentation depth and rebuttals.' },
      { title: 'Round 3 — Grand Finale', description: 'Is Marriage Becoming Obsolete in Modern Society? Championship round with the full judging panel.' },
    ],
    rules: [
      'Strictly follow allocated time limits for each speaking slot',
      'Respectful conduct toward judges opponents and audience is mandatory',
      'No mobile phones or internet during preparation or speaking',
      'Topics disclosed 15 minutes before each round',
      'Judges decision is final and binding',
      'Arrive 15 minutes before scheduled start time',
    ],
    judging_criteria: [
      'Confidence & Stage Presence',
      'Clarity of Thought',
      'Speaking Skills',
      'Critical Thinking',
      'Logical Reasoning',
      'Rebuttals',
      'Time Management',
      'Overall Impact',
    ],
    thumbnail_image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=400&q=80',
    banner_image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1600&q=80',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    registration_enabled: true,
    slots_total: 50,
    slots_filled: 0,
    display_order: 1,
  },
  {
    id: 'poetry-reciting',
    title: 'Poetry Reciting',
    short_description: 'Let your words paint worlds. Express what words alone cannot.',
    description: 'A celebration of the written and spoken word. Bring your original or classic poetry to life on stage and move hearts with your verses.',
    date: '2026-03-16',
    time: '2:00 PM – 5:00 PM',
    location: 'Seminar Hall',
    category: 'Literary',
    registration_fee_single: 99,
    registration_fee_team: null,
    team_size_min: 1,
    team_size_max: 1,
    team_size: 'Individual',
    prize: 'Exciting Gifts + Certificate',
    google_form_url: 'https://forms.gle/gRye4xaCtEpuXWLc7',
    rules: [
      'Original or published poems are both allowed',
      'Maximum 5 minutes per performance',
      'No offensive or political content',
      'Props are allowed on stage',
      'Judges decision is final',
    ],
    judging_criteria: [
      'Expression & Emotion',
      'Voice Modulation',
      'Content Quality',
      'Stage Presence',
      'Audience Engagement',
    ],
    thumbnail_image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=400&q=80',
    banner_image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1600&q=80',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    registration_enabled: true,
    slots_total: 40,
    slots_filled: 0,
    display_order: 2,
  },
  {
    id: 'pitch-perfect',
    title: 'Pitch Perfect',
    short_description: 'Got a startup idea? Pitch it. Win it. Live it.',
    description: 'Present your business idea to a panel of expert judges. Whether it is a tech startup, social enterprise, or creative venture — if you have a vision, VOXERA is your launchpad.',
    date: '2026-03-17',
    time: '10:00 AM – 1:00 PM',
    location: 'Conference Room',
    category: 'Management',
    registration_fee_single: 50,
    registration_fee_team: 50,
    team_size_min: 1,
    team_size_max: 4,
    team_size: '1-4',
    prize: 'Exciting Gifts + Certificate',
    google_form_url: 'https://forms.gle/B5xCvuGFv33ZDaS8A',
    rules: [
      '5 minute pitch followed by 3 minute Q&A',
      'PPT or slides presentation is allowed',
      'No pre-recorded video pitches',
      'Maximum 4 team members',
      'Business model must be original and your own',
    ],
    judging_criteria: [
      'Innovation & Originality',
      'Feasibility',
      'Market Potential',
      'Presentation Quality',
      'Team Coordination',
    ],
    thumbnail_image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=400&q=80',
    banner_image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1600&q=80',
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    registration_enabled: true,
    slots_total: 30,
    slots_filled: 0,
    display_order: 3,
  },
  {
    id: 'open-mic',
    title: 'Open Mic',
    short_description: 'Your stage. Your voice. Your moment. No rules — just you.',
    description: 'Comedy, spoken word, music, beatboxing, impressions — if it can be performed, bring it to the Open Mic stage. This is your moment to own the room.',
    date: '2026-03-17',
    time: '3:00 PM – 6:00 PM',
    location: 'Main Auditorium',
    category: 'Cultural',
    registration_fee_single: 99,
    registration_fee_team: 150,
    team_size_min: 1,
    team_size_max: 2,
    team_size: '1-2',
    prize: 'Goodies + Certificate',
    google_form_url: 'https://forms.gle/eKtGg9opFuhR4sm2A',
    rules: [
      'Maximum 7 minutes per act',
      'No offensive political or explicit content',
      'Original content is strongly preferred',
      'Musical instruments and props are allowed',
      'Sound check mandatory 30 minutes before the event',
    ],
    judging_criteria: [
      'Stage Presence',
      'Originality',
      'Audience Engagement',
      'Delivery',
      'Overall Impact',
    ],
    thumbnail_image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80',
    banner_image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1600&q=80',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    registration_enabled: true,
    slots_total: 25,
    slots_filled: 0,
    display_order: 4,
  },
  {
    id: 'treasure-hunt',
    title: 'Treasure Hunt',
    short_description: 'Solve riddles. Beat the clock. Find the treasure first.',
    description: 'A campus-wide hunt packed with puzzles, riddles, and physical challenges. Rally your team of 4 and race to be the first to find the final treasure.',
    date: '2026-03-16',
    time: '9:00 AM – 12:00 PM',
    location: 'Campus-wide',
    category: 'Informal',
    registration_fee_single: 120,
    registration_fee_team: 120,
    team_size_min: 4,
    team_size_max: 4,
    team_size: 'Team of 4',
    prize: 'Exciting Gifts + Certificate',
    google_form_url: 'https://forms.gle/UcnLKWUsiSKGEjbx6',
    rules: [
      'Exactly 4 members required per team',
      'No outside help or internet access allowed',
      'All clues must be solved strictly in order',
      'Damaging any property results in immediate disqualification',
      'Organizer decisions are final',
    ],
    judging_criteria: [
      'Speed',
      'Accuracy',
      'Teamwork',
      'Clues Completed',
    ],
    thumbnail_image: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=400&q=80',
    banner_image: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1600&q=80',
    image: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    registration_enabled: true,
    slots_total: 20,
    slots_filled: 0,
    display_order: 5,
  },
  {
    id: 'film-screening',
    title: 'Film Screening',
    short_description: 'Three iconic films. One unforgettable experience. Grab your popcorn.',
    description: 'VOXERA presents an exclusive Film Screening event — a cinematic journey featuring three carefully curated films that celebrate friendship, ambition, and the power of thinking differently. Sit back, relax, and let the magic of cinema inspire you.',
    date: '2026-03-17',
    time: '1:00 PM – 7:00 PM',
    location: 'Main Auditorium',
    category: 'Cultural',
    registration_fee_single: 80,
    registration_fee_team: null,
    team_size_min: 1,
    team_size_max: 1,
    team_size: 'Individual',
    prize: 'An Unforgettable Experience',
    google_form_url: null,
    rounds: [
      { title: '🎬 Screening 1 — Chhichhore', description: 'A heartwarming Bollywood blockbuster that celebrates friendship, failure, and the spirit of never giving up. Relive the hostel days and learn that losers of today are the winners of tomorrow.', fee: 80, google_form_url: 'https://forms.gle/ZaBVJsPnbwD5GrjGA' },
      { title: '🎬 Screening 2 — Dead Poets Society', description: 'A timeless classic starring Robin Williams. A story about seizing the day, thinking for yourself, and the transformative power of poetry and education. "Carpe Diem!"', fee: 80, google_form_url: 'https://forms.gle/jZ6qgTbDCcKD3ihg9' },
      { title: '🎬 Screening 3 — To Be Announced', description: 'The final film is a surprise! Stay tuned — we\'re saving the best reveal for last. Follow our socials for the big announcement.', fee: 80 },
    ],
    rules: [
      'Entry is on a first-come, first-served basis',
      'Maintain silence during screenings',
      'No recording or photography during the films',
      'Discussion sessions may follow each screening',
      'Food and beverages may be available at the venue',
    ],
    judging_criteria: [],
    thumbnail_image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=400&q=80',
    banner_image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1600&q=80',
    image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    registration_enabled: true,
    slots_total: null,
    slots_filled: 0,
    display_order: 6,
  },
];

async function seed() {
  console.log('🌱 Seeding VOXERA 2026 database (upsert mode)...');

  try {
    for (const event of seedEvents) {
      const eventData = {
        id: event.id,
        title: event.title,
        description: event.description,
        short_description: event.short_description,
        date: event.date,
        time: event.time,
        location: event.location,
        category: event.category,
        image: event.image,
        banner_image: event.banner_image,
        thumbnail_image: event.thumbnail_image,
        rules: event.rules,
        team_size: event.team_size,
        prize: event.prize,
        registration_fee_single: event.registration_fee_single,
        registration_fee_team: event.registration_fee_team,
        team_size_min: event.team_size_min,
        team_size_max: event.team_size_max,
        registration_enabled: event.registration_enabled,
        is_published: event.is_published,
        google_form_url: event.google_form_url,
        slots_total: event.slots_total,
        slots_filled: event.slots_filled,
        rounds: (event as any).rounds || null,
        judging_criteria: event.judging_criteria,
        coordinators: [],
        display_order: event.display_order,
        created_at: new Date(),
        updated_at: new Date(),
      };

      await db.insert(schema.events).values(eventData)
        .onConflictDoUpdate({
          target: schema.events.id,
          set: {
            title: eventData.title,
            description: eventData.description,
            short_description: eventData.short_description,
            date: eventData.date,
            time: eventData.time,
            location: eventData.location,
            category: eventData.category,
            image: eventData.image,
            banner_image: eventData.banner_image,
            thumbnail_image: eventData.thumbnail_image,
            rules: eventData.rules,
            team_size: eventData.team_size,
            prize: eventData.prize,
            registration_fee_single: eventData.registration_fee_single,
            registration_fee_team: eventData.registration_fee_team,
            team_size_min: eventData.team_size_min,
            team_size_max: eventData.team_size_max,
            registration_enabled: eventData.registration_enabled,
            is_published: eventData.is_published,
            google_form_url: eventData.google_form_url,
            slots_total: eventData.slots_total,
            rounds: eventData.rounds,
            judging_criteria: eventData.judging_criteria,
            coordinators: eventData.coordinators,
            display_order: eventData.display_order,
            updated_at: new Date(),
          },
        });

      console.log(`  ✅ Upserted: ${event.title}`);
    }

    console.log(`\n🎉 Seeded/updated ${seedEvents.length} events successfully.`);
  } catch (err) {
    console.error('❌ Seed failed:', err);
    process.exit(1);
  }

  process.exit(0);
}

seed();
